### ISSUE TITLE
permission denied on startup

### ISSUE THREAD

**Issue by braddevans** [rmichela/Bukkit-SSHD#9]
i made the rsa key as per the install guide according to the linux guide
and i am on the latest version of the plugin;

[20:48:32] [Server thread/INFO]: [SSHD] Enabling SSHD v1.2
[20:48:35] [Server thread/ERROR]: [SSHD] Failed to start SSH server! Permission denied

i also made the jar file executable 
chmod a+rwx sshd.jar

but it may be a problem with my current user permissions

[SSHD.zip](https://github.com/rmichela/Bukkit-SSHD/files/1908748/SSHD.zip)

**Comment by toxuin** [comment]
It seems like you're not allowed to start a server on port 22. In your config file, set `port` to something else like `25505` and try restarting it again.

Is this happening on a shared service or on a local machine?

**Comment by Haarolean** [comment]
Consider reopening if that doesn't help.
